### ISSUE TITLE
README所述导入方式疑似有误

### ISSUE THREAD

**Issue by samotoo** [rsuite/charts#19]
**Describe the bug**
按照README中描述导入并使用组件，报错。

**To Reproduce**
1. 创建create-react-app项目。
2. 安装必要依赖。
3. 使用`import { LineChart } from "@rsuite/charts";`导入组件，并在render函数中渲染组件。
4. 启动项目，错误显示导入的项目为undefined。

**Expected behavior**
没有报错，组件正常渲染；或者修改README。

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75

**Additional context**
直接用绝对路径导入相应组件是可以正常工作的，貌似`index.js`中只导出了default，并没有其他的命名导出。

**Comment by SevenOutman** [comment]
@samotoo 确认 README 中描述有误。

为减小打包体积，`@rsuite/charts` 中组件的导入方式参考了 `echarts` 的按需导入。
`<LineChart>` 的导入方式应为：

```jsx
import LineChart from '@rsuite/charts/lib/charts/LineChart';
```

其他各组件也分别位于 `lib/charts/` `lib/series` `lib/components` 目录下。
