### ISSUE TITLE
缺少 axisLabel 属性的简易 formatter 用法声明

### ISSUE THREAD

**Issue by LeiHanCN** [rsuite/charts#23]
**Describe the bug**
缺少 axisLabel 属性的简易 formatter 用法声明

**To Reproduce**

**Expected behavior**
在使用 axisLabel 快捷用法的时候不再出现声明报错
```tsx
const formatter = (value: string) => 'hello'
...
<YAxis axisLabel={formatter}/>
```
**Screenshots**
![image](https://user-images.githubusercontent.com/19839331/72506189-63d19080-387c-11ea-9d54-d7edb2fcb91f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
相关官方文档：https://charts.rsuitejs.com/#%E7%89%B9%E6%AE%8A%20props

**Comment by SevenOutman** [comment]
fixed in #24
