### ISSUE TITLE
YAxis 设定 splitLine 属性部分失效

### ISSUE THREAD

**Issue by LeiHanCN** [rsuite/charts#25]
**Describe the bug**
YAxis 设定 splitLine 属性部分失效

**To Reproduce**
```tsx
// 下面的 splitLine 都失效
<YAxis minInterval={30000} axisLabel={true} splitLine={{ interval: 1 }} /> 
<YAxis minInterval={30000} axisLabel={true} splitLine={{ lineStyle: { width: 30 } }} />

// 下面生效
<YAxis minInterval={30000} axisLabel={true} splitLine={false} /> 
```

**Expected behavior**
上述案例都生效

**Screenshots**
![image](https://user-images.githubusercontent.com/19839331/72509498-aac28480-3882-11ea-9c00-2af79b122926.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SevenOutman** [comment]
fixed in #24
