### ISSUE TITLE
Toolbox 

### ISSUE THREAD

**Issue by antonymarion** [rsuite/charts#31]
Hello,

Is there the possibility to use the nice toolbox from original echarts lib ?
https://echarts.apache.org/en/option.html#toolbox

regards,
Antony

**Comment by SevenOutman** [comment]
There's not yet a `<Toolbox>` component out there, but we may include it in future releases if we start to use it often. As a workaround for now, you can pass your options with toolbox into `<ECharts>` component which fully supports ECharts options.
