### ISSUE TITLE
ECharts import statement

### ISSUE THREAD

**Issue by ShiriNmi1520** [rsuite/charts#63]
**Description**
ECharts have breaking changes about its [import statement](https://echarts.apache.org/handbook/en/basics/release-note/v5-upgrade-guide/).
But it seems like rsuite_light.ts & rsuite_dark.ts still remains the default import statement
(src/theme/rsuite_light.ts & src/theme/rsuite_dark.ts)
```
import echarts from 'echarts/lib/echarts';
const theme = {
... remain of code
```
Which should be changed by following refer to EChart upgrade guide
```
import * as echarts from 'echarts/lib/echarts';
const theme = {
... remain of code
```

**Comment by ShiriNmi1520** [comment]
I've to see @MarvelSQ created #51 related to this issue but seems not merged yet :/

**Comment by SevenOutman** [comment]
It's now supported in 5.1.0
