### ISSUE TITLE
[MapChart] Empty data throw Error

### ISSUE THREAD

**Issue by MarvelSQ** [rsuite/charts#88]
**Describe the bug**
while data is empty, MapChart throw Error

**To Reproduce**

https://codesandbox.io/s/epic-satoshi-dhxdql?file=/src/App.tsx

**Expected behavior**

show empty view

**Screenshots**

![Screenshot 2023-07-17 at 14 34 26](https://github.com/rsuite/charts/assets/14308293/bf0fbc92-ec45-43a0-899a-b2fd20fa80cf)

**Comment by SevenOutman** [comment]
Released in [`@rsuite/charts@5.2.1`](https://github.com/rsuite/charts/releases/tag/%40rsuite%2Fcharts%405.2.1)
