### ISSUE TITLE
@rsuite/charts: TypeScript definitions are missing in the NPM package

### ISSUE THREAD

**Issue by yurist38** [rsuite/charts#93]
**Describe the bug**
I've noticed that starting from version `5.2.1` of the NPM package `@rsuite/charts`, no `d.ts` files are shipped. So I can't properly use this package in my TS project anymore. Probably something got changed in your TS configuration or the builder.

**To Reproduce**

1. Install the latest version of the NPM package `@rsuite/charts`
2. Check the distribution folder.

**Expected behavior**
Supposed to be a `.d.ts` file with TypeScript definitions in the root folder

**Screenshots**
<img width="357" alt="Screenshot 2023-08-01 at 13 56 37" src="https://github.com/rsuite/charts/assets/10692413/79c59854-6893-4c80-862a-60976e4dae28">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: any
- Version: 13.4.1

**Comment by SevenOutman** [comment]
Looks like our docs site's building artifacts override the package bundle files. I've just published [`@rsuite/charts@5.2.3`](https://www.npmjs.com/package/@rsuite/charts/v/5.2.3) with correct package files, please try out and see if the problem is resolved.

I'm leaving this issue open as we still need to fix the publish workflow to prevent similar mistakes.

**Comment by yurist38** [comment]
Lovely! Thanks a lot for the quick fix! I confirm that the latest version `5.2.3` contains type definitions.

**Comment by electroheadfx** [comment]
Any news ? I can't anymore get types from `5.69`:

- `import { type ItemDataType } from 'rsuite/esm/@types/common'`
- `import { type MessageType } from 'rsuite/esm/Notification/index'`
-  ...

**Comment by simonguo** [comment]
Hi @electroheadfx  
The current repository is a discussion about the problems encountered in `@rsuite/charts`. Please go to the [rsuite issues](https://github.com/rsuite/rsuite/issues) and explain in detail when you will use `MessageType` and `ItemDataType` in what scenarios.

**Comment by electroheadfx** [comment]
thanks
