### ISSUE TITLE
I need help using MapChart

### ISSUE THREAD

**Issue by ItaloCobains** [rsuite/charts#95]
I am looking for some graphics library to use in my project, luckily I found yours and I need to use a map graphic.
![image](https://github.com/rsuite/charts/assets/83548040/f98328ca-5f49-4735-a954-7907d56f359a)

I looked at the examples you provided and I'm kind of lost.
I would like to replicate the map for Brazil. Can you help me or provide a guide?

I really enjoyed the design live. I think it would be interesting to make the documentation available in English for greater accessibility.

My discord if you want to talk to me: italowCobains#0001

**Comment by SevenOutman** [comment]
Hi @ItaloCobains thanks for liking this library!

To use the MapChart, first you need to prepare the GeoJSON data for the map you want to render, and register it with a name in ECharts. In the example below, the GeoJSON data for a China map is registered as `"china"`. After the map data is registered, specify `map` prop of MapChart as the name of the registered maps you want to display, and the map should be rendered.

<img width="623" alt="image" src="https://github.com/rsuite/charts/assets/8225666/d08891bf-7955-434a-8803-d28a15866564">

To add data to the map, pass it to the `data` prop of MapChart. The structure of the data should be an entry map of name of each region and the data value.

<img width="476" alt="image" src="https://github.com/rsuite/charts/assets/8225666/fce14cd4-d80e-4b84-9d5a-409a378567ea">

You can also click on the "Toggle source code panel" button at the bottom-right corder of each example on the docs site to see the actual code for running the examples.

<img width="212" alt="image" src="https://github.com/rsuite/charts/assets/8225666/cd8e4375-e640-4c12-add0-0a252b620590">

Hope it helps!

**Comment by ItaloCobains** [comment]
![image](https://github.com/rsuite/charts/assets/83548040/f34cc45c-900f-4ee5-939c-fed3d851665c)
Thank you, for the guide I was able to understand the flow and apply. I would like to try translating the docs to pt-BR how can I do that? of course if you want.

**Comment by SevenOutman** [comment]
> I would like to try translating the docs to pt-BR how can I do that? of course if you want.

Thank you for being willing to contribute. But we don't plan to have a translation of our docs in a language that we're not familiar with - we won't be able to review the content and keep it up-to-date.

**Comment by ItaloCobains** [comment]
So I understand your decision. Thanks.
