### ISSUE TITLE
MapChart with %

### ISSUE THREAD

**Issue by ItaloCobains** [rsuite/charts#96]
Hi, @SevenOutman 

I'm trying to put a string in the value of each state a number with % at the end in string format and I'm having this error. Does the library support  this?

![image](https://github.com/rsuite/charts/assets/83548040/124b5a3d-651d-4717-b308-fb46d2ccb4da)

**Comment by SevenOutman** [comment]
Could you provide example code that reproduces this issue?

**Comment by ItaloCobains** [comment]
![image](https://github.com/rsuite/charts/assets/83548040/cb87886e-bb31-4a1d-9b01-49fb3e3bad61)
Just add this to some json field

https://codesandbox.io/s/solitary-river-tkckfr?file=/basic.json

**Comment by SevenOutman** [comment]
The MapChart only accepts numeric values. If you want to display the values as percentage on the tooltip, you can use `tooltip.valueFormatter` option from ECharts.

```jsx
<MapChart
  name="覆盖率"
  map="china"
  data={data}
  tooltip={{
    valueFormatter: (value) => `${value}%`
  }}
/>
```

Working CodeSandbox: https://codesandbox.io/s/wonderful-darkness-rxsgjd
ECharts docs: https://echarts.apache.org/en/option.html#series-map.tooltip.valueFormatter

**Comment by ItaloCobains** [comment]
It worked, thank you.
