### ISSUE TITLE
how to change message of empty data in LineChart and MapChart ?

### ISSUE THREAD

**Issue by ItaloCobains** [rsuite/charts#97]
Hi, @SevenOutman 
I want change the message of empty data to other language. How to make this ?

![image](https://github.com/rsuite/charts/assets/83548040/8c386c7b-86fd-440f-9443-9b6bca04e400)

**Comment by SevenOutman** [comment]
There is a `locale` prop on ECharts or any *Chart component you import from `@rsuite/charts`, which is for specifying these messages. Available messages are:

```typescript
type ChartProps = {
  locale?: {
    /**
     * Message to display when chart data is empty.
     */
    emptyMessage?: React.ReactNode;
    /**
     * Message to display when `loading=true`
     */
    loading?: React.ReactNode;
  }
}
```

Reference: https://charts.rsuitejs.com/api#echarts

**Comment by ItaloCobains** [comment]
Thank you. @SevenOutman
