### ISSUE TITLE
Chart overlaying another chart

### ISSUE THREAD

**Issue by ItaloCobains** [rsuite/charts#98]
Hi, @SevenOutman 

I need to do something similar to a graphics overlay on my website.

Example would like that when the user clicked on a state in the map graph another graph would appear on top of it showing the cities derived from that state.

Does the library support this or is there a way for you to know how to do this?

**Comment by SevenOutman** [comment]
`@rsuite/charts` does not provide more functionality around charts than ECharts - the charts library it's based on. You may need to search whether ECharts supports drilling down. Alternatively, you can refer to [ECharts API docs about events](https://echarts.apache.org/en/api.html#events) to see if there's some events you can make use of to detect user clicking a state on the map.
