### ISSUE TITLE
How to make graphics responsive?

### ISSUE THREAD

**Issue by ItaloCobains** [rsuite/charts#99]
How to make graphics responsive?

![image](https://github.com/rsuite/charts/assets/83548040/ce3fc862-2e15-476a-a3a7-e32719cb3aef)

**Comment by SevenOutman** [comment]
`@rsuite/charts` does not have built-in responsiveness. You can refer to ECharts docs about how to make it responsive.

**Comment by ItaloCobains** [comment]
thank you.
